const week_2 = [
  { text: "document.createElement" },
  { text: ".map()" },
  { text: ".filter()" },
  { text: ".reduce()" },
  { text: ".forEach()" },
  { text: ".concat()" },
  { text: "callback function" },
  { text: "fetch" },
  { text: "try/catch/finally" },
  { text: "Promise" },
  { text: ".then()" },
  { text: "dreamer room" },
  { text: "realist room" },
  { text: "spoiler room" },
  { text: "JSON.parse()" },
  { text: "JSON.stringify()" },
  { text: "api" },
  { text: "api" },
  { text: "git add ." },
  { text: "git commit" },
  { text: "git push" },
  { text: "console.dir()" },
  { text: "console.log()" },
  { text: "console.error()" },
  { text: "console.warn()" },
  { text: "Error()" }
];
